const {load}=require('./mock_gas');
const {ctx,sheets}=load();
const get=p=>JSON.parse(ctx.doGet({parameter:p}).getContent());
const post=p=>JSON.parse(ctx.doPost({postData:{contents:JSON.stringify(p)}}).getContent());
let fails=0;const ok=(c,m)=>{if(!c){fails++;console.log('FAIL',m);}else console.log('ok  ',m);};
ok(get({action:'ping'}).ok,'ping');
ok(get({action:'load',id:'a'}).error==='bad_id','짧은 ID 거부');
ok(get({action:'load',id:'홍 길동'}).error==='bad_id','공백 ID 거부');
ok(get({action:'load',id:'히포우'}).exists===false,'없는 ID는 exists=false');
let r=post({action:'save',id:'히포우',updatedAt:1000,data:{money:12345,wins:2,losses:1,bestPts:230,week:2,up:{shoes:1,snack:0,sneak:1}}});
ok(r.ok&&r.created,'새 ID 저장(created)');
r=get({action:'load',id:'히포우'});
ok(r.exists&&r.data.money===12345&&r.data.up.shoes===1,'저장한 데이터 불러오기');
r=get({action:'load',id:'히포우'.toUpperCase()});ok(r.exists,'대소문자/동일 ID 조회');
r=post({action:'save',id:'ABCd',updatedAt:1000,data:{money:5000}});
r=get({action:'load',id:'abcD'});ok(r.exists&&r.name==='ABCd','ID 대소문자 무시 + 표시 이름 유지');
r=post({action:'save',id:'히포우',updatedAt:2000,data:{money:20000,wins:3,bestPts:400,week:3}});
ok(r.ok&&!r.conflict,'더 최신 저장 성공');
r=post({action:'save',id:'히포우',updatedAt:1500,data:{money:1,wins:0}});
ok(r.conflict&&r.data.money===20000,'오래된 기기는 충돌(최신 데이터 반환)');
r=post({action:'save',id:'히포우',updatedAt:3000,data:{money:9e15,wins:'x',up:{shoes:99}}});
const d=get({action:'load',id:'히포우'}).data;
ok(d.money===100000000&&d.wins===0&&d.up.shoes===3,'값 범위 보정(치트/오류 방지)');
r=post({action:'save',id:'히포우',updatedAt:4000,data:{money:1000,note:'x'.repeat(9000)}});
ok(r.ok,'허용되지 않은 필드는 버리고 저장');
post({action:'score',id:'히포우',bet:1500,goals:3,pts:330,result:'승리',money:11500,week:2});
ok(sheets.Matches&&sheets.Matches.rows.length===2,'Matches 로그 1건 추가');
post({action:'save',id:'짱구',updatedAt:1,data:{money:7000,wins:9,bestPts:900}});
post({action:'save',id:'철수',updatedAt:1,data:{money:30000,wins:1,bestPts:100}});
let t=get({action:'top',metric:'money',limit:3});
ok(t.list[0].id==='철수'&&t.list.length===3,'소지금 랭킹 1위');
t=get({action:'top',metric:'wins'});ok(t.list[0].id==='짱구','승리 랭킹 1위');
t=get({action:'top',metric:'bestPts'});ok(t.list[0].id==='짱구','최고점 랭킹 1위');
ok(get({action:'zzz'}).error==='unknown_action','알 수 없는 action');
console.log('\nUsers 시트 헤더:',sheets.Users.rows[0].join(' | '));
console.log(fails?('실패 '+fails+'건'):'전부 통과');
process.exit(fails?1:0);
